kind: PersistentVolume
apiVersion: v1
metadata:
  name: devpod-pv
  labels:
    type: devpod
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/tomxu/devpods/share"